[project]
name = "py-ai-fastapi-chat"
version = "0.1.0"
description = "Chat demo using Python Vercel AI SDK with FastAPI"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.1",
    "vercel-ai-sdk",
]

[tool.uv.sources]
vercel-ai-sdk = { path = "../../..", editable = true }
